#!/bin/bash -e

if [ -z "${PLTUSERHOME}" ]; then
	export PLTUSERHOME="${PWD}"
fi

export pkgsdir="${RPM_BUILD_ROOT}/usr/share/racket/extra-pkgs"
export docsdir="${RPM_BUILD_ROOT}/usr/share/doc/racket"

mkdir -p "${pkgsdir}"
mkdir -p "${docsdir}"

for path in "${@}"; do
	pushd "${path}"

	name="$(basename "${PWD}")"

	mkdir -p "${pkgsdir}/${name}"
	tar -cpf- --exclude='doc' . | tar -xf- -C "${pkgsdir}/${name}"

	find . -type f -name out0.sxref -printf '%h\n' \
	| while read module; do
		cp -R "${module}" "${docsdir}/"
	done

	popd
done

# EOF
