#!/bin/bash -e

export PLTUSERHOME="${PWD}"

export pkgsdir="${RPM_BUILD_ROOT}/usr/share/racket/extra-pkgs"
export docsdir="${RPM_BUILD_ROOT}/usr/share/doc/racket"

export srcdir="${PLTUSERHOME}"/.racket/*/pkgs/"${1}"

mkdir -p "${pkgsdir}"
mkdir -p "${docsdir}"

mkdir -p "${pkgsdir}/${1}"
tar -xzf "${1}.tgz" --exclude='doc' -C "${pkgsdir}/${1}"
tar -xzf "${1}.tgz" -C "${docsdir}" '*/doc' --strip-components=2

# EOF
