#!/bin/bash -e

export PLTUSERHOME="${PWD}"

mkdir -p .source
mv * .source/

raco pkg install --force --user --deps fail --copy --name "${1}" .source

find .racket/ -type f -name '*.html' \
       -exec sed -e 's#<script[^>]*/local-user-redirect.js"[^>]*></script>##g' \
                 -i {} \;

raco pkg create --format tgz --built --from-install --dest . "${1}"

# EOF
